/* Copyright (c) 2017 dbradly. All rights reserved. */

package dbrad.jacocoverage.plugin.config.ep;

import dbrad.jacocoverage.plugin.config.projconfig.PrjcfgAntJavasePanel;
import dbrad.jacocofpm.config.IdeProjectJacocoverageConfig;
import dbrad.jacocofpm.mgr.com.NbProjectJacoco;
import dbrad.jacocoverage.plugin.util.NbUtilsPlugin;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import org.netbeans.api.project.Project;
import org.openide.util.Exceptions;

/**
 *
 * @author dbradley
 */
public class EpJPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 0L;

    public PrjcfgAntJavasePanel prjCfgPanel;

    public IdeProjectJacocoverageConfig prjCfg;

    /**
     * Creates new form EpJPanel
     */
    public EpJPanel() {
        initComponents();
    }

    //99
    /**
     *
     * @param prjCfgPanel     configuration panel needed for the store()
     */
    public void setProjectConfig(PrjcfgAntJavasePanel prjCfgPanel) {
        this.prjCfgPanel = prjCfgPanel;

        try {
            this.prjCfg = IdeProjectJacocoverageConfig.reuseForProject(prjCfgPanel.nbProjectJacoco.getPrincipleNbProject());

            // .forFile(prjCfgPanel.nbProjectJacoco.prjCfgFile);
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
    }

    public void loadExcludePackagesFromJson(NbProjectJacoco nbProjectJacoco) {
        jTableExcludePackages.setupAndBuild(new EpJTableDatum(nbProjectJacoco, this));
        jTableExcludePackages.loadTableFromProjectJson(prjCfg);
    }

    public void storeExcludePackages() {
        HashMap<String, Boolean> excludePkgs = prjCfg.jsonMapData.getExcludePackages();
        excludePkgs.clear();

        jTableExcludePackages.excludesPackagesTableToMap(excludePkgs);
    }

    /**
     * Do a save of data of the exclude packages setting and store it to the
     * Json file.
     */
    void saveToJson() {
        // 
        this.prjCfgPanel.store();

        // when the EpJTable is stored there is an impact to the tables
        // as well
        NbProjectJacoco nbPrjJac = this.prjCfg.nbProjectJacoco;
        Project proj = nbPrjJac.getPrincipleNbProject();

        ArrayList<String> excludeList = NbUtilsPlugin.getExcludesPatternsAsArrayList(proj);
        nbPrjJac.mergeAllSourcesForDisplay(excludeList);
        
        nbPrjJac.repaint4Project();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exclErrorMessageLabel = new javax.swing.JLabel();
        epTextField1 = new dbrad.jacocoverage.plugin.config.ep.EpTextField();
        epAddButt = new dbrad.jacocoverage.plugin.config.ep.EpAddButt();
        jPanel3 = new javax.swing.JPanel();
        jCheckBoxExcludedOrgTestng = new javax.swing.JCheckBox();
        jCheckBoxExcludedOrgJunit = new javax.swing.JCheckBox();
        jCheckBoxExcludedJunitExtension = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        epRemoveButt1 = new dbrad.jacocoverage.plugin.config.ep.EpRemoveButt();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableExcludePackages = new dbrad.jacocoverage.plugin.config.ep.EpJTable();

        jPanel1.setMaximumSize(new java.awt.Dimension(50, 50));
        jPanel1.setMinimumSize(new java.awt.Dimension(50, 50));

        org.openide.awt.Mnemonics.setLocalizedText(exclErrorMessageLabel, org.openide.util.NbBundle.getMessage(EpJPanel.class, "EpJPanel.exclErrorMessageLabel.text")); // NOI18N

        epTextField1.setText(org.openide.util.NbBundle.getMessage(EpJPanel.class, "EpJPanel.epTextField1.text")); // NOI18N

        epAddButt.setMnemonic('A');
        org.openide.awt.Mnemonics.setLocalizedText(epAddButt, org.openide.util.NbBundle.getMessage(EpJPanel.class, "EpJPanel.epAddButt.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(exclErrorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(epAddButt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(epTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(exclErrorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epAddButt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(epTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        epTextField1.addKeyListener(epAddButt);
        epAddButt.setPrgCfgData(this);
        epAddButt.addActionListener(epAddButt);

        jCheckBoxExcludedOrgTestng.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxExcludedOrgTestng, org.openide.util.NbBundle.getMessage(EpJPanel.class, "EpJPanel.jCheckBoxExcludedOrgTestng.text")); // NOI18N
        jCheckBoxExcludedOrgTestng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxExcludedOrgTestngActionPerformed(evt);
            }
        });

        jCheckBoxExcludedOrgJunit.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxExcludedOrgJunit, org.openide.util.NbBundle.getMessage(EpJPanel.class, "EpJPanel.jCheckBoxExcludedOrgJunit.text")); // NOI18N
        jCheckBoxExcludedOrgJunit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxExcludedOrgJunitActionPerformed(evt);
            }
        });

        jCheckBoxExcludedJunitExtension.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxExcludedJunitExtension, org.openide.util.NbBundle.getMessage(EpJPanel.class, "EpJPanel.jCheckBoxExcludedJunitExtension.text")); // NOI18N
        jCheckBoxExcludedJunitExtension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxExcludedJunitExtensionActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(EpJPanel.class, "EpJPanel.jLabel2.text")); // NOI18N

        epRemoveButt1.setMnemonic('1');
        org.openide.awt.Mnemonics.setLocalizedText(epRemoveButt1, org.openide.util.NbBundle.getMessage(EpJPanel.class, "EpJPanel.epRemoveButt1.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxExcludedOrgTestng)
                            .addComponent(jCheckBoxExcludedOrgJunit)
                            .addComponent(jCheckBoxExcludedJunitExtension)
                            .addComponent(epRemoveButt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(epRemoveButt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jCheckBoxExcludedOrgTestng)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxExcludedOrgJunit)
                .addGap(2, 2, 2)
                .addComponent(jCheckBoxExcludedJunitExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        epRemoveButt1.setPrgCfgData(this);
        epRemoveButt1.addActionListener(epRemoveButt1);

        jTableExcludePackages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableExcludePackages);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxExcludedOrgTestngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxExcludedOrgTestngActionPerformed
        prjCfgPanel.store();
    }//GEN-LAST:event_jCheckBoxExcludedOrgTestngActionPerformed

    private void jCheckBoxExcludedOrgJunitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxExcludedOrgJunitActionPerformed
        prjCfgPanel.store();
    }//GEN-LAST:event_jCheckBoxExcludedOrgJunitActionPerformed

    private void jCheckBoxExcludedJunitExtensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxExcludedJunitExtensionActionPerformed
        prjCfgPanel.store();
    }//GEN-LAST:event_jCheckBoxExcludedJunitExtensionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public dbrad.jacocoverage.plugin.config.ep.EpAddButt epAddButt;
    public dbrad.jacocoverage.plugin.config.ep.EpRemoveButt epRemoveButt1;
    public dbrad.jacocoverage.plugin.config.ep.EpTextField epTextField1;
    public javax.swing.JLabel exclErrorMessageLabel;
    public javax.swing.JCheckBox jCheckBoxExcludedJunitExtension;
    public javax.swing.JCheckBox jCheckBoxExcludedOrgJunit;
    public javax.swing.JCheckBox jCheckBoxExcludedOrgTestng;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    public dbrad.jacocoverage.plugin.config.ep.EpJTable jTableExcludePackages;
    // End of variables declaration//GEN-END:variables
}
